name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1
      with:
        github_access_token: ${{ secrets.DEPLOY_SECRET }}
        build_configuration: production
        base_href: /ed-yt-relations/
        deploy_branch: deploy
        angular_dist_build_folder: dist/
